# Generated by Django 2.1.7 on 2019-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_singular', models.CharField(max_length=255)),
                ('display_plural', models.CharField(max_length=255)),
                ('allows_decimal', models.BooleanField()),
            ],
            options={
                'db_table': 'measure_unit',
            },
        ),
        migrations.CreateModel(
            name='PaymentCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days_offset', models.IntegerField()),
            ],
            options={
                'db_table': 'payment_condition',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
