# Generated by Django 2.1.7 on 2019-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura'), ('COTIZACION', 'Cotizacion')], max_length=15, unique=True)),
                ('series', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'document_counter',
            },
        ),
    ]
