# Generated by Django 2.1.7 on 2019-03-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'identity_document',
            },
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('web', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'persona_juridica',
            },
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_number', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('identity_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.IdentityDocument')),
            ],
            options={
                'db_table': 'persona_natural',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Contact')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PersonaNatural')),
            ],
            options={
                'db_table': 'representante',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='juridica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PersonaJuridica'),
        ),
        migrations.AddField(
            model_name='contact',
            name='natural',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PersonaNatural'),
        ),
    ]
